enableGlobalCache: true

packageExtensions:
  "@sapphire/decorators@*":
    dependencies:
      "@sapphire/discord.js-utilities": "*"
      "@sapphire/framework": "*"
      discord.js: ^13.10.3
  "@sapphire/discord.js-utilities@*":
    dependencies:
      discord-api-types: "*"
      discord.js: ^13.10.3
  "@sapphire/framework@*":
    dependencies:
      "@discordjs/builders": "*"
      discord.js: ^13.10.3

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
