enableGlobalCache: true

packageExtensions:
  "@sapphire/decorators@*":
    dependencies:
      "@sapphire/discord.js-utilities": "*"
      "@sapphire/framework": "*"
      discord.js: "^13.8.1"
  "@sapphire/discord.js-utilities@*":
    dependencies:
      discord-api-types: "*"
      discord.js: "^13.8.1"
  "@sapphire/framework@*":
    dependencies:
      "@discordjs/builders": "*"
      discord.js: "^13.8.1"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
